version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
        - POSTGRES_USER=postgre
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=bannerlord
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_SOURCE=postgresql://postgre:1234@postgres:5432/bannerlord?sslmode=disable