postgres:
  postgres_host: 'localhost'
  postgres_db_name: 'bannerlord'
  users_db_name: "users"
  postgres_user_name: 'postgres'
  postgres_password: '1234'
  postgres_port: '5433'
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "5433"
  password: "1234"