postgres:
  postgres_host: 'localhost'
  postgres_db_name: 'postgres'
  postgres_user_name: 'postgres'
  postgres_password: 'postgres'
  postgres_port: '5432'
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "Shabby8574"
  password: "Huy"